baseURL: "/"
languageCode: en-us
title: SurejAJ's Notes
copyRight: "Surej Joseph"

module:
  imports:
  - path: github.com/panr/hugo-theme-terminal

menus:
  main:
  - identifier: "home"
    name: "Home"
    url: "/"

  - identifier: "aboutme"
    name: "About Me"
    url: "/aboutme"

params:
  contentTypeName: "posts"
  themeColor: blue
  fullWidthTheme: false
  centerTheme: true
  showMenuItems: 2

  languages:
    en:
      languageName: "English"
      owner: "Surej Joseph"
      copyright: ""
      fullWidthTheme: false
      centerTheme: true

  logo:
    logoText: "SurejAJ's Notes"
