baseURL: "/"
languageCode: en-us
title: UBoot Notes
theme: terminal
params:
  contentTypeName: "posts"
  themeColor: orange
  fullWidthTheme: false
  centerTheme: true
  showMenuItems: 2

  languages:
    en:
      languageName: "English"
      owner: "Surej Joseph"
      copyright: ""
      fullWidthTheme: false
      centerTheme: true
