baseURL: "/"
languageCode: en-us
title: SurejAJ's Notes.
copyRight: "Surej Joseph"

module:
  imports:
  - path: github.com/panr/hugo-theme-terminal

params:
  contentTypeName: "posts"
  themeColor: green
  fullWidthTheme: false
  centerTheme: true
  showMenuItems: 2

  menu:
    main:
      identifier: "home"
      name: "Home"
      url: "/"

      identifier: "aboutme"
      name: "About Me"
      url: "/about"

  logo:
    logoText: "SurejAJ's Notes"
